=== WebDaD/lib-songbeamer/docs/song.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://lib-songbeamer.com/song.json",
  "type": "object",
  "properties": {
    "slides": {
      "$id": "/properties/slides",
      "type": "array",
      "items": {
        "$id": "/properties/slides/items",
        "type": "object",
        "properties": {
          "lines": {
            "$id": "/properties/slides/items/properties/lines",
            "type": "array",
            "items": {
              "$id": "/properties/slides/items/properties/lines/items",
              "type": "string",
              "title": "The 0 Schema",
              "description": "A Line of Song-Text",
              "default": "",
              "examples": [
                "Our Father everlasting,"
              ]
            }
          },
          "caption": {
            "$id": "/properties/slides/items/properties/caption",
            "type": "string",
            "title": "The Caption Schema",
            "description": "The Caption of a Slide.",
            "default": "",
            "examples": [
              "Verse 1"
            ]
          }
        }
      }
    },
    "LangCount": {
      "$id": "/properties/LangCount",
      "type": "string",
      "title": "The Langcount Schema",
      "description": "How many Languages are there",
      "default": "",
      "examples": [
        "2"
      ]
    },
    "Title": {
      "$id": "/properties/Title",
      "type": "string",
      "title": "The Title Schema",
      "description": "Original Title of the Song",
      "default": "",
      "examples": [
        "This I Believe (The Creed)"
      ]
    },
    "Editor": {
      "$id": "/properties/Editor",
      "type": "string",
      "title": "The Editor Schema",
      "description": "How was this created.",
      "default": "",
      "examples": [
        "SongBeamer 4.14a"
      ]
    },
    "Version": {
      "$id": "/properties/Version",
      "type": "string",
      "title": "The Version Schema",
      "description": "Version of this Song.",
      "default": "",
      "examples": [
        "3"
      ]
    },
    "TitleFormat": {
      "$id": "/properties/TitleFormat",
      "type": "string",
      "title": "The Titleformat Schema",
      "description": "How the Title is formatted",
      "default": "",
      "examples": [
        "U"
      ]
    },
    "BackgroundImage": {
      "$id": "/properties/BackgroundImage",
      "type": "string",
      "title": "The Backgroundimage Schema",
      "description": "Path to the bg-image",
      "default": "",
      "examples": [
        "bgvideos://Blanko fï¿½r Songbeamer-1.jpg"
      ]
    },
    "(c)": {
      "$id": "/properties/(c)",
      "type": "string",
      "title": "The (c) Schema",
      "description": "Copyrights",
      "default": "",
      "examples": [
        "Hillsong Worship"
      ]
    },
    "Translation": {
      "$id": "/properties/Translation",
      "type": "string",
      "title": "The Translation Schema",
      "description": "Name of the translators",
      "default": "",
      "examples": [
        "Martin Bruch & Dennis Strehl"
      ]
    },
    "Author": {
      "$id": "/properties/Author",
      "type": "string",
      "title": "The Author Schema",
      "description": "Name of the Text-Author.",
      "default": "",
      "examples": [
        "Ben Fielding & Matthew Crocker"
      ]
    },
    "Melody": {
      "$id": "/properties/Melody",
      "type": "string",
      "title": "The Melody Schema",
      "description": "Name of the Melody-Author.",
      "default": "",
      "examples": [
        "Ben Fielding & Matthew Crocker"
      ]
    },
    "TitleLang2": {
      "$id": "/properties/TitleLang2",
      "type": "string",
      "title": "The Titlelang2 Schema",
      "description": "Second Title in different Language",
      "default": "",
      "examples": [
        "Das glaube ich"
      ]
    },
    "VerseOrder": {
      "$id": "/properties/VerseOrder",
      "type": "string",
      "title": "The Verseorder Schema",
      "description": "Order of Slides, by captions",
      "default": "",
      "examples": [
        "Verse 1,Chorus,Verse 2,Chorus,Bridge,Chorus"
      ]
    }
  }
}

=== WebDaD/lib-songbeamer/tests/data/song.json
{"slides":[{"lines":["Our Father everlasting,","Ich glaube an den Vater,","the all creating One,","den Sch�pfer aller Welt,","God Almighty.","Gott allm�chtig."],"caption":"Verse 1"},{"lines":["Through Your Holy Spirit","Durch Gottes Geist empfangen","conceiving Christ the Son,","kam Christus in die Welt,","Jesus, our Saviour.","Jesus, mein Retter."]},{"lines":["I believe in God our Father","Ja, ich glaub an Gott, den Vater","I believe in Christ the Son","Und an Christus, Seinen Sohn","I believe in the Holy Spirit","An den Heiligen Geist der Wahrheit","Our God is three in One","An den dreieinen Gott"],"caption":"Chorus"},{"lines":["I believe in the resurrection","Ja, ich glaub an die Auferstehung","That we will rise again","Das Leben nach dem Tod","For I believe in the Name of Jesus","Ich glaube an Deinen Namen, Jesus"]},{"lines":["Our judge and our defender","Mein Richter und mein Anwalt","Suffered and crucified","Gekreuzigt unter Leid","Forgiveness is in You","Vergebung ist in Dir"],"caption":"Verse 2"},{"lines":["Descended into darkness","Du stiegst ins Reich der Toten","You rose in glorious life","Standst auf in Herrlichkeit","Forever seated high","Und herrschst in Ewigkeit"]},{"lines":["I believe in You","Ja, ich glaub an Dich","I believe You rose again","Dass Du auferstanden bist","I believe that Jesus Christ is Lord","Ja, ich glaub an Christus, unsern Herrn","2x","2x"],"caption":"Bridge"},{"lines":["I believe in life eternal","Ja, ich glaub, dass wir ewig leben","I believe in the virgin birth","Dass die Jungfrau den Sohn gebar","I believe in the saints' communion","Die Gemeinschaft der Kinder Gottes","And in Your holy Church","Die Kirche unsres Herrn"]},{"lines":["I believe in the resurrection","Ja, ich glaub an die Auferstehung","When Jesus comes again","Wenn Jesus wiederkommt","For I believe in the Name of Jesus","Ich glaube an Deinen Namen, Jesus"]},{"lines":["I believe in You","Ja, ich glaub an Dich","I believe You rose again","Dass Du auferstanden bist","I believe that Jesus Christ is Lord","Ja, ich glaub an Christus, unsern Herrn","2x","2x",""]}],"LangCount":"2","Title":"This I Believe (The Creed)","Editor":"SongBeamer 4.14a","Version":"3","TitleFormat":"U","BackgroundImage":"bgvideos://Blanko f�r Songbeamer-1.jpg","(c)":"Hillsong Worship","Translation":"Martin Bruch & Dennis Strehl","Author":"Ben Fielding & Matthew Crocker","Melody":"Ben Fielding & Matthew Crocker","TitleLang2":"Das glaube ich","VerseOrder":"Verse 1,Chorus,Verse 2,Chorus,Bridge,Chorus"}
